version: '3.9'
services: 
# MongoDB services
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    restart: always
    volumes: 
      - ./database:/data/db
    networks:
      - nesjs-network

  # Nest App Service
  dev:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      dockerfile: ./Dockerfile
      context: .
    command: npm run start:dev
    ports:
      - 3000:3000
    networks:
      - nesjs-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  
  # prod:
  #   container_name: nestjs_api_prod
  #   image: nestjs-api-prod:1.0.0
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   command: npm run start:prod
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - nesjs-network
  #   depends_on:
  #     - mongodb
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules

networks:
  nesjs-network:
    driver: bridge

volumes:
  mongodb: {}

